version: '3.9'
services:
  DB:
    image: mysql:${MYSQL_VERSION}
    ports:
      - "${MYSQL_EXPOSE_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PWD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: Asia/Bangkok
    volumes:
      - "./.docker/init.sql:/docker-entrypoint-initdb.d/init.sql"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_EXPOSE_PORT}:1323"
    env_file:
      - .env
    depends_on:
      DB:
        condition: service_healthy
